language: bash
sudo: required
env:
  global:
  - TRAVIS_CI_OPERATOR=1
  - secure: "VPjEK6qVG1Moofe1DizvbEevQA3aVcr+SPJfN3cD8qaxl7acuOIyApZUv2MuI+uGCvccxLMFg+Xpgvs1PmMMPlwFf8B9Vj/xzOycfrUlFNS9cnxM/CxzmnUuAzis2YNmrf60bPTHWCV2fji+bbxLV/24/V1TLnPvn6k1c6CmTFAxAHy5SfPebC4kRyUt4OzvieFsYGZXSGhj4MZoRgvrH3RiMzXy3XZJpR59JrxNSWqEvhVumnIG15cQjccJk9A+ooaWwfssciX+PicvBd46dbN4kqCKizJcZ1SWfApMPefwtwgevI1bkAKEnYoeQ95Riptms/T0jw49+KrN6/iw3VHeHuzSxZaPQXKdnd0nlVvcPVnKESCv4KPi/WKA+HJo34+6482nVdrP7sd7wJvdtA+ag/N3rpPoefTHaNSKoBtXdaBbv7DjJv0xRaGx8IqjyyMU9dMkm/vNIxSHct2dn+Q5Fl4tJGAxyzUM7vlDoc1Nm31Wbl1juh8jh11K6Q0q2v2A7gXb+Ql5q/M5k40H/Z47EC7LBTZbG5K49uzypNzR71YpwoEl6Q+rVYoIfm3NBs9aRlq5A/twRb2zsZBPjYf+M83/LDM9tIkZ0au7pPqprZEp7Kaj4/f9vB4BXry+hvIhE6SSk8w3bba96w2vxa9CDaQNBPt6zbbdZi7JLiY="
  - secure: "e6oPLCypssNeJCq5d+ms3XJCcQIBtnShB5vrpTkoPmoFMAVug1vwi+sY7M2xAKTQ8XB0/puW2gR6bX93JAe9aft00Qx10/j+YZU8hUcp07H1I1OzZ/SxFWq/WLp0Jq/jWYpFhaBXOUnvZnf1KlqY216YwafwTkdMVr4GysqkKadwOp5wSJKKDxSVotCzOHVLWh1/UI0KhNx/mMT+wMWzWBkjrInDmUoR/ay0r7Q9outXC3qgpE6AbS7IrdLoi5Y9F6MyzSSPGR1KCCoC1uQJ4yvtiqC8PhvOqCJRFfg2qciMWeq2T31tACt8HS857bltEomHR9/YYDAmVCdOKRV4ZxvXltrVLEn9+PFnYFINRNUgRfG4lCALByBPMvCgdVeeAPT8q2JohcPAsob5IBVKWSh/IIooSLMC/95B3arxnU9S7HKqpxbWvAe0nli8TdO8ks3Fye37mwtPgVItr9T4clj6hrBnuKKL1DfZCiSK7EiHw4lpW2lxw4o91GzXgtZBAJQQmz/gG1NrCfdf3CHGOxyMygYG55RtICOfaHEXv7C6L66FfCa5RZCQV3KJ9j7+PTTEoNpPhKvzq0MV1R545oF5A+WLTg+jkkapt49zDIBXfP0r7UIlhIKI08dBtraSmndU+/N1VTzXOIRKNy10EacaxMG+vLLIjk3j2e0f0fQ="
services:
- docker
install:
- curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
- bash $HOME/bin/travis_ci_operator.sh init
- travis_ci_operator.sh docker-login
script:
- docker pull uumpa/knesset-data-backend:latest
- docker build -t uumpa/knesset-data-backend:latest -t uumpa/knesset-data-backend:$TRAVIS_COMMIT --cache-from uumpa/knesset-data-backend:latest .
deploy:
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
    condition: $TRAVIS_TAG = "" && $TRAVIS_PULL_REQUEST = "false"
